- hosts: all 
  remote_user: gor
  become: yes
  become_method: sudo
  tasks: 
    - name: Update & upgrade apt 
      apt:
        upgrade: yes
        update_cache: yes
    - name: install nginx 
      apt:
       name: 
         - nginx
       state: present
    - service: 
        name: nginx
        state: started
