---
- name: Second Task Ansible 
  hosts: all 
  become: yes
  tasks:
  - name:
    apt: 
      name:
        - tuned
      state: present 
  - name: tuned as demon 
    service: 
      name: tuned 
      state: restarted 
      enabled: yes 
      
     
      
